export const ships = {
  fighter: {
    name: "Fighter",
    attack: 12,
    defense: 8,
    health: 50,
    energy: 20,
    special1: "Boost Attack",
    special2: "Weaken Attack",
    image: "/brand/ships/fighter.png",
  },
  defender: {
    name: "Defender",
    attack: 8,
    defense: 12,
    health: 50,
    energy: 20,
    special1: "Boost Defense",
    special2: "Weaken Defense",
    image: "/brand/ships/defender.png",
  },
  healer: {
    name: "Healer",
    attack: 8,
    defense: 8,
    health: 50,
    energy: 25,
    special1: "Heal",
    special2: "Recharge Energy",
    image: "/brand/ships/healer.png",
  },
  scout: {
    name: "Scout",
    attack: 10,
    defense: 10,
    health: 40,
    energy: 30,
    special1: "Double Strike",
    special2: "Weaken Defense",
    image: "/brand/ships/scout.png",
  },
  assassin: {
    name: "Assassin",
    attack: 14,
    defense: 6,
    health: 40,
    energy: 20,
    special1: "Multiple Strike",
    special2: "Weaken Attack",
    image: "/brand/ships/assassin.png",
  },
  tank: {
    name: "Tank",
    attack: 6,
    defense: 14,
    health: 60,
    energy: 20,
    special1: "Boost Defense",
    special2: "Heal",
    image: "/brand/ships/tank.png",
  },
  support: {
    name: "Support",
    attack: 8,
    defense: 8,
    health: 50,
    energy: 30,
    special1: "Recharge Energy",
    special2: "Boost Attack",
    image: "/brand/ships/support.png",
  },
  sniper: {
    name: "Sniper",
    attack: 16,
    defense: 4,
    health: 40,
    energy: 20,
    special1: "Multiple Strike",
    special2: "Weaken Defense",
    image: "/brand/ships/sniper.png",
  },
  shielder: {
    name: "Shielder",
    attack: 6,
    defense: 10,
    health: 50,
    energy: 25,
    special1: "Boost Defense",
    special2: "Weaken Attack",
    image: "/brand/ships/shielder.png",
  },
  berserker: {
    name: "Berserker",
    attack: 14,
    defense: 7,
    health: 45,
    energy: 20,
    special1: "Boost Attack",
    special2: "Multiple Strike",
    image: "/brand/ships/berserker.png",
  },
};

export const shipImages = {
  fighter: "/brand/ships/fighter.png",
  defender: "/brand/ships/defender.png",
  healer: "/brand/ships/healer.png",
  scout: "/brand/ships/scout.png",
  assassin: "/brand/ships/assassin.png",
  tank: "/brand/ships/tank.png",
  support: "/brand/ships/support.png",
  sniper: "/brand/ships/sniper.png",
  shielder: "/brand/ships/shielder.png",
  berserker: "/brand/ships/berserker.png",
};

export const player2ShipImages = {
  fighter: "/brand/ships/fighter-2.png",
  defender: "/brand/ships/defender-2.png",
  healer: "/brand/ships/healer-2.png",
  scout: "/brand/ships/scout-2.png",
  assassin: "/brand/ships/assassin-2.png",
  tank: "/brand/ships/tank-2.png",
  support: "/brand/ships/support-2.png",
  sniper: "/brand/ships/sniper-2.png",
  shielder: "/brand/ships/shielder-2.png",
  berserker: "/brand/ships/berserker-2.png",
};
